import type {
  Connection,
  Finding,
  HealthScore,
  ScanRun,
  DomainScan,
  ScanDomain,
  Severity,
  AiReport,
  DomainMetadata,
} from './types';

export const mockDomainMetadata: DomainMetadata[] = [
  {
    domain: 'AUTOMATION',
    label: 'Automações',
    description:
      'Automations com status, schedules e histórico de execução. Detecta falhas silenciosas e processos órfãos.',
    estimatedApiCalls: 3,
    estimatedDurationSeconds: 10,
    minimumPlan: 'FREE',
    ruleCount: 4,
    scoreWeight: 0.15,
    protocol: 'REST',
  },
  {
    domain: 'DATA',
    label: 'Dados',
    description:
      'Data Extensions, campos, retention policies e primary keys. Detecta duplicidades, naming e DEs sem governança.',
    estimatedApiCalls: 2,
    estimatedDurationSeconds: 25,
    minimumPlan: 'FREE',
    ruleCount: 5,
    scoreWeight: 0.2,
    protocol: 'SOAP',
  },
  {
    domain: 'EMAIL',
    label: 'Email Setup',
    description:
      'Send Classifications, Delivery Profiles, Send Definitions e Triggered Sends. Identifica configurações incompletas.',
    estimatedApiCalls: 4,
    estimatedDurationSeconds: 20,
    minimumPlan: 'PRO',
    ruleCount: 3,
    scoreWeight: 0.15,
    protocol: 'SOAP',
  },
  {
    domain: 'GOVERNANCE',
    label: 'Governança',
    description:
      'Business Units, usuários, roles e Installed Packages. Avalia ownership, excesso de admins e packages sem uso.',
    estimatedApiCalls: 4,
    estimatedDurationSeconds: 15,
    minimumPlan: 'FREE',
    ruleCount: 4,
    scoreWeight: 0.2,
    protocol: 'SOAP',
  },
  {
    domain: 'JOURNEY',
    label: 'Jornadas',
    description:
      'Journeys ativas, pausadas e drafts. Identifica conteúdo obsoleto e artefatos esquecidos.',
    estimatedApiCalls: 3,
    estimatedDurationSeconds: 10,
    minimumPlan: 'FREE',
    ruleCount: 3,
    scoreWeight: 0.15,
    protocol: 'REST',
  },
  {
    domain: 'SECURITY',
    label: 'Segurança',
    description:
      'Installed Packages e scopes. Detecta escopos excessivos, ausência de rotação e combinações perigosas.',
    estimatedApiCalls: 1,
    estimatedDurationSeconds: 8,
    minimumPlan: 'PRO',
    ruleCount: 3,
    scoreWeight: 0.15,
    protocol: 'SOAP',
  },
];


function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const mockConnections: Connection[] = [
  {
    id: 'conn-demo-1',
    name: 'Produção — Acme Corp',
    subdomain: 'mc6xxxxxxxxxxxxxxxxxx',
    accountId: '7891234',
    clientId: 'abc123def456ghi789',
    integrationType: 'MULTI_BU',
    status: 'ACTIVE',
    lastTestedAt: daysAgo(0),
    errorMessage: null,
    createdAt: daysAgo(45),
  },
  {
    id: 'conn-demo-2',
    name: 'Sandbox',
    subdomain: 'mc7yyyyyyyyyyyyyyyyyy',
    accountId: '7891235',
    clientId: 'xyz789uvw456rst123',
    integrationType: 'SINGLE_BU',
    status: 'FAILED',
    lastTestedAt: daysAgo(2),
    errorMessage: 'Falha ao autenticar com o SFMC',
    createdAt: daysAgo(10),
  },
];

const mockDomainScans: DomainScan[] = [
  { id: 'd1', domain: 'GOVERNANCE', status: 'COMPLETED', itemsCollected: 34, errorMessage: null, startedAt: daysAgo(1), completedAt: daysAgo(1) },
  { id: 'd2', domain: 'DATA', status: 'COMPLETED', itemsCollected: 127, errorMessage: null, startedAt: daysAgo(1), completedAt: daysAgo(1) },
  { id: 'd3', domain: 'JOURNEY', status: 'COMPLETED', itemsCollected: 42, errorMessage: null, startedAt: daysAgo(1), completedAt: daysAgo(1) },
  { id: 'd4', domain: 'AUTOMATION', status: 'COMPLETED', itemsCollected: 28, errorMessage: null, startedAt: daysAgo(1), completedAt: daysAgo(1) },
  { id: 'd5', domain: 'EMAIL', status: 'COMPLETED', itemsCollected: 56, errorMessage: null, startedAt: daysAgo(1), completedAt: daysAgo(1) },
  { id: 'd6', domain: 'SECURITY', status: 'COMPLETED', itemsCollected: 4, errorMessage: null, startedAt: daysAgo(1), completedAt: daysAgo(1) },
];

export const mockHealthScore: HealthScore = {
  id: 'score-demo-1',
  scanRunId: 'scan-demo-1',
  scoreOverall: 72.4,
  scoreGovernance: 85,
  scoreData: 55,
  scoreJourney: 78,
  scoreAutomation: 62,
  scoreEmail: 80,
  scoreSecurity: 75,
  classification: 'Risco',
  totalFindings: 23,
  criticalCount: 2,
  highCount: 7,
  mediumCount: 10,
  lowCount: 4,
};

function f(overrides: Partial<Finding>): Finding {
  return {
    id: Math.random().toString(36).slice(2),
    ruleId: 'DATA-001',
    category: 'DATA',
    severity: 'HIGH',
    objectType: 'DataExtension',
    objectId: null,
    objectName: null,
    evidence: '',
    ruleViolated: '',
    impact: '',
    recommendation: '',
    effort: 'MEDIUM',
    priority: 140,
    status: 'OPEN',
    createdAt: daysAgo(1),
    ...overrides,
  };
}

export const mockFindings: Finding[] = [
  f({
    ruleId: 'AUT-001',
    category: 'AUTOMATION',
    severity: 'CRITICAL',
    objectType: 'Automation',
    objectName: 'Nightly_Customer_Sync',
    evidence: 'Última execução terminou em estado: Error',
    ruleViolated: 'Automations não devem terminar em estado de erro',
    impact: 'Processos de negócio interrompidos silenciosamente',
    recommendation: 'Investigar logs e corrigir a causa raiz da falha',
    priority: 200,
  }),
  f({
    ruleId: 'SEC-001',
    category: 'SECURITY',
    severity: 'CRITICAL',
    objectType: 'InstalledPackage',
    objectName: 'Legacy_API_Integration',
    evidence: '6/8 escopos são de escrita: data_extensions_write, data_extensions_create, journeys_modify, email_send, automations_write, contacts_delete',
    ruleViolated: 'Packages devem ter apenas os escopos estritamente necessários',
    impact: 'Credencial comprometida pode alterar dados produtivos do SFMC',
    recommendation: 'Revisar escopos e remover os de escrita que não forem usados',
    effort: 'MEDIUM',
    priority: 200,
  }),
  f({
    ruleId: 'DATA-001',
    category: 'DATA',
    severity: 'HIGH',
    objectType: 'DataExtension',
    objectName: 'Newsletter_Subscribers_2023',
    evidence: 'Data Extension sem retention policy configurada',
    ruleViolated: 'Toda DE deve ter política de retenção de dados',
    impact: 'Armazenamento crescente indefinido, risco de LGPD/GDPR',
    recommendation: 'Configurar retention policy adequada ao caso de uso',
    effort: 'LOW',
    priority: 210,
  }),
  f({
    ruleId: 'DATA-001',
    category: 'DATA',
    severity: 'HIGH',
    objectType: 'DataExtension',
    objectName: 'Campaign_Response_Historical',
    evidence: 'Data Extension sem retention policy configurada',
    ruleViolated: 'Toda DE deve ter política de retenção de dados',
    impact: 'Armazenamento crescente indefinido, risco de LGPD/GDPR',
    recommendation: 'Configurar retention policy adequada ao caso de uso',
    effort: 'LOW',
    priority: 210,
  }),
  f({
    ruleId: 'DATA-002',
    category: 'DATA',
    severity: 'HIGH',
    objectType: 'DataExtension',
    objectName: 'Product_Catalog_Extended',
    evidence: 'Data Extension sem primary key definida',
    ruleViolated: 'Data Extensions devem ter primary key para evitar duplicidade',
    impact: 'Registros duplicados, inconsistência em lookups e jornadas',
    recommendation: 'Definir primary key apropriada na DE',
    priority: 140,
  }),
  f({
    ruleId: 'JRN-001',
    category: 'JOURNEY',
    severity: 'HIGH',
    objectType: 'Journey',
    objectName: 'Welcome Series — BR',
    evidence: 'Journey ativa há 223 dias sem modificação',
    ruleViolated: 'Journeys ativas devem ser revisadas ao menos a cada 180 dias',
    impact: 'Conteúdo obsoleto entregue aos contatos, ROI decrescente',
    recommendation: 'Revisar conteúdo, entradas e saídas da journey',
    priority: 140,
  }),
  f({
    ruleId: 'EML-002',
    category: 'EMAIL',
    severity: 'HIGH',
    objectType: 'SendClassification',
    objectName: 'Default Commercial',
    evidence: 'Send Classification sem Delivery Profile vinculado',
    ruleViolated: 'Send Classifications devem ter Delivery Profile associado',
    impact: 'Envios podem usar configuração incorreta de header/footer/IP',
    recommendation: 'Associar Delivery Profile apropriado à Send Classification',
    effort: 'LOW',
    priority: 210,
  }),
  f({
    ruleId: 'GOV-002',
    category: 'GOVERNANCE',
    severity: 'HIGH',
    objectType: 'Account',
    objectName: 'Account-level',
    evidence: '8/22 usuários ativos são admin (36%)',
    ruleViolated: 'Admins não devem ultrapassar 20% dos usuários ativos',
    impact: 'Risco de alterações não autorizadas e dificuldade de auditoria',
    recommendation: 'Revogar role Admin de usuários que não precisam; usar roles customizadas',
    priority: 140,
  }),
  f({
    ruleId: 'SEC-002',
    category: 'SECURITY',
    severity: 'HIGH',
    objectType: 'InstalledPackage',
    objectName: 'Legacy_API_Integration',
    evidence: 'Package sem modificação há 423 dias',
    ruleViolated: 'Client secrets devem ser rotacionados ao menos uma vez por ano',
    impact: 'Aumenta janela de exposição caso o secret seja comprometido',
    recommendation: 'Rotacionar client secret e atualizar a conexão no MC Pulse',
    effort: 'LOW',
    priority: 210,
  }),
  f({
    ruleId: 'DATA-003',
    category: 'DATA',
    severity: 'MEDIUM',
    objectType: 'DataExtension',
    objectName: 'temp_testing_de',
    evidence: 'Nome "temp_testing_de" não segue convenção de prefixo (ex: DE_, STG_)',
    ruleViolated: 'Data Extensions devem seguir convenção de nomenclatura',
    impact: 'Dificuldade de governança e busca',
    recommendation: 'Padronizar nomes com prefixos por tipo/ambiente',
    priority: 80,
  }),
  f({
    ruleId: 'AUT-002',
    category: 'AUTOMATION',
    severity: 'MEDIUM',
    objectType: 'Automation',
    objectName: 'Data_Enrichment_Manual',
    evidence: 'Automation ativa sem schedule configurado',
    ruleViolated: 'Automations recorrentes devem ter schedule ou trigger definido',
    impact: 'Execução manual ou ausência de execução causa falhas operacionais',
    recommendation: 'Definir schedule ou documentar motivo de execução manual',
    effort: 'LOW',
    priority: 120,
  }),
  f({
    ruleId: 'JRN-002',
    category: 'JOURNEY',
    severity: 'MEDIUM',
    objectType: 'Journey',
    objectName: 'Black Friday 2024 — Retarget',
    evidence: 'Journey pausada há 94 dias',
    ruleViolated: 'Journeys pausadas devem ser retomadas, arquivadas ou excluídas',
    impact: 'Acúmulo de artefatos sem propósito claro',
    recommendation: 'Decidir pelo arquivamento ou reativação da journey',
    effort: 'LOW',
    priority: 120,
  }),
  f({
    ruleId: 'GOV-001',
    category: 'GOVERNANCE',
    severity: 'MEDIUM',
    objectType: 'InstalledPackage',
    objectName: 'Zapier_Integration',
    evidence: 'Package possui 12 escopos ativos',
    ruleViolated: 'Installed Package não deve ter mais de 10 escopos',
    impact: 'Superfície de ataque ampliada; violação do princípio de menor privilégio',
    recommendation: 'Revisar e reduzir escopos ao mínimo necessário',
    priority: 80,
  }),
  f({
    ruleId: 'AUT-003',
    category: 'AUTOMATION',
    severity: 'LOW',
    objectType: 'Automation',
    objectName: 'Old_Import_Routine',
    evidence: 'Automation sem descrição/documentação',
    ruleViolated: 'Automations devem ter descrição clara do propósito',
    impact: 'Dificuldade de manutenção e onboarding de novos membros',
    recommendation: 'Adicionar descrição explicando propósito e dependências',
    effort: 'LOW',
    priority: 60,
  }),
  f({
    ruleId: 'DATA-005',
    category: 'DATA',
    severity: 'LOW',
    objectType: 'DataExtension',
    objectName: 'Customer_Master_Extended',
    evidence: 'DE possui 78 campos',
    ruleViolated: 'DEs devem ser granulares — máximo recomendado 50 campos',
    impact: 'Performance degradada em queries e SSJS',
    recommendation: 'Normalizar: dividir em DEs menores e relacioná-las',
    effort: 'HIGH',
    priority: 20,
  }),
];

export const mockScanRuns: ScanRun[] = [
  {
    id: 'scan-demo-1',
    status: 'COMPLETED',
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    createdAt: daysAgo(1),
    connectionId: 'conn-demo-1',
    domainScans: mockDomainScans,
    healthScore: mockHealthScore,
  },
  {
    id: 'scan-demo-old-1',
    status: 'COMPLETED',
    startedAt: daysAgo(14),
    completedAt: daysAgo(14),
    createdAt: daysAgo(14),
    connectionId: 'conn-demo-1',
    domainScans: mockDomainScans,
    healthScore: { ...mockHealthScore, scoreOverall: 65.2, classification: 'Risco', totalFindings: 31, criticalCount: 4, highCount: 9 },
  },
];

export const mockAiReport: AiReport = {
  id: 'ai-demo-1',
  status: 'COMPLETED',
  executiveSummary:
    'O ambiente Salesforce Marketing Cloud da Acme Corp apresenta sinais claros de envelhecimento técnico sem uma rotina de higienização proporcional ao seu volume de uso. O score geral de 72 — classificado como "Risco" — é puxado principalmente pela ausência de políticas de retenção em Data Extensions críticas e por escopos excessivamente amplos em pacotes de integração legados.\n\nOs dois riscos mais urgentes são a automação Nightly_Customer_Sync falhando silenciosamente há pelo menos 24 horas (impacto direto em dados de clientes desatualizados) e o pacote Legacy_API_Integration concentrando escopos de escrita e leitura simultâneos, o que amplia materialmente o raio de explosão de qualquer comprometimento de credencial. Há também um desvio de governança: 36% dos usuários ativos têm role Admin, muito acima do limite saudável de 20%.\n\nRecomendamos atacar primeiro a automação quebrada (investigação imediata) e em paralelo abrir um plano de 30 dias para rotação de credenciais e redução de escopos do pacote legado. Os achados de dados (retention policies ausentes) podem ser endereçados em batch em ciclo de 60 dias com impacto significativo na conformidade LGPD.',
  technicalAnalysis:
    '### Governança\nAmbiente com 22 usuários ativos e 8 admins — proporção acima do recomendado. O pacote Zapier_Integration está com 12 escopos, ligeiramente acima do limite. Padrão geral saudável exceto pelo excesso de admins.\n\n### Dados\nO domínio mais penalizado. 9 Data Extensions sem retention policy (várias com mais de 2 anos de dados acumulados), 4 DEs sem primary key e 3 com nomes fora do padrão. Sugere ausência de template de criação de DE e falta de data governance formal.\n\n### Jornadas\nJourney "Welcome Series — BR" ativa há 223 dias sem revisão — conteúdo muito provavelmente desatualizado. Uma journey pausada de Black Friday 2024 ainda consta como pausada, não arquivada.\n\n### Automações\nFalha crítica em Nightly_Customer_Sync. Uma automation sem schedule (Data_Enrichment_Manual) e duas sem descrição. Sugere ausência de runbook operacional.\n\n### Email\nSendClassification "Default Commercial" sem Delivery Profile associado — risco de envios com configuração incorreta de header/IP. 3 triggered sends ativas sem atividade recente.\n\n### Segurança\nRisco alto: pacote Legacy_API_Integration com mix de escopos de escrita + leitura há mais de 400 dias sem rotação de credencial. Combinação típica de "conta de serviço universal" que deveria ser dividida.',
  actionPlan30:
    '## 30 dias — Urgências\n\n1. **Investigar falha em Nightly_Customer_Sync** [AUT-001] — acionar responsável hoje, levantar logs, corrigir ou isolar.\n2. **Rotacionar client secret** do Legacy_API_Integration [SEC-002] e atualizar a conexão no MC Pulse.\n3. **Associar Delivery Profile** à SendClassification "Default Commercial" [EML-002].\n4. **Configurar retention policy** nas 2 DEs mais antigas [DATA-001] — começar por Newsletter_Subscribers_2023 e Campaign_Response_Historical.',
  actionPlan60:
    '## 31–60 dias — Estruturação\n\n1. **Reduzir escopos** do pacote Legacy_API_Integration [SEC-001] removendo os de escrita desnecessários.\n2. **Revisar Welcome Series — BR** [JRN-001] — auditar conteúdo, atualizar se ativa, arquivar se obsoleta.\n3. **Plano de redução de admins**: revogar role Admin de usuários que não precisam [GOV-002].\n4. **Definir primary keys** nas 4 DEs sem PK [DATA-002].\n5. **Aplicar retention policy** nas 7 DEs restantes sem política [DATA-001].',
  actionPlan90:
    '## 61–90 dias — Higienização\n\n1. **Refatorar Customer_Master_Extended** dividindo em DEs menores [DATA-005].\n2. **Padronizar nomenclatura** de todas as DEs fora do padrão [DATA-003].\n3. **Arquivar ou reativar** journeys pausadas antigas [JRN-002].\n4. **Documentar** automations sem descrição [AUT-003] — escrever runbook.\n5. **Revisar Zapier_Integration** — reduzir para ≤10 escopos [GOV-001].',
  operationalChecklist:
    '## Checklist operacional\n\n- [ ] [AUT-001] Nightly_Customer_Sync — responsável: **Ops** — esforço: Médio — prazo: 2 dias\n- [ ] [SEC-002] Rotação de client secret Legacy_API_Integration — responsável: **Security** — esforço: Baixo — prazo: 7 dias\n- [ ] [EML-002] Associar Delivery Profile — responsável: **Marketing Ops** — esforço: Baixo — prazo: 3 dias\n- [ ] [DATA-001] Retention Newsletter_Subscribers_2023 — responsável: **Data Team** — esforço: Baixo — prazo: 7 dias\n- [ ] [DATA-001] Retention Campaign_Response_Historical — responsável: **Data Team** — esforço: Baixo — prazo: 7 dias\n- [ ] [SEC-001] Reduzir escopos Legacy_API_Integration — responsável: **Security** — esforço: Médio — prazo: 30 dias\n- [ ] [JRN-001] Revisar Welcome Series — responsável: **CRM** — esforço: Médio — prazo: 30 dias\n- [ ] [GOV-002] Reduzir % de admins — responsável: **SFMC Admin** — esforço: Médio — prazo: 45 dias',
  generatedAt: daysAgo(1),
};

// Scan "em execução" fictício para o usuário ver o SSE animar
export function createRunningScan(): ScanRun {
  return {
    id: `scan-running-${Date.now()}`,
    status: 'RUNNING',
    startedAt: new Date().toISOString(),
    completedAt: null,
    createdAt: new Date().toISOString(),
    connectionId: 'conn-demo-1',
    healthScore: null,
    domainScans: [
      { id: 'rd1', domain: 'GOVERNANCE', status: 'PENDING', itemsCollected: 0, errorMessage: null, startedAt: null, completedAt: null },
      { id: 'rd2', domain: 'DATA', status: 'PENDING', itemsCollected: 0, errorMessage: null, startedAt: null, completedAt: null },
      { id: 'rd3', domain: 'JOURNEY', status: 'PENDING', itemsCollected: 0, errorMessage: null, startedAt: null, completedAt: null },
      { id: 'rd4', domain: 'AUTOMATION', status: 'PENDING', itemsCollected: 0, errorMessage: null, startedAt: null, completedAt: null },
      { id: 'rd5', domain: 'EMAIL', status: 'PENDING', itemsCollected: 0, errorMessage: null, startedAt: null, completedAt: null },
      { id: 'rd6', domain: 'SECURITY', status: 'PENDING', itemsCollected: 0, errorMessage: null, startedAt: null, completedAt: null },
    ],
  };
}

export const ALL_DOMAINS: ScanDomain[] = [
  'GOVERNANCE',
  'DATA',
  'JOURNEY',
  'AUTOMATION',
  'EMAIL',
  'SECURITY',
];

export type { Severity };
